# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Trial2Cure-V2-2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    # Checkout code with Git LFS support
    - name: Install Git LFS
      run: git lfs install

    - name: Pull Git LFS Files
      run: git lfs pull

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://t2cacrv2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c3747ab976864998a9d8e76a373e111c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e57f2d6bfd4b4f8c82f4061fe1574d1d }}

    # Build and push Docker container
    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: t2cacrv2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c3747ab976864998a9d8e76a373e111c }}/t2c-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    # Deploy to Azure Web App
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Trial2Cure-V2-2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6cfd6f63f6ae40cf8e82a9699dc0e9c2 }}
        images: 't2cacrv2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c3747ab976864998a9d8e76a373e111c }}/t2c-image:${{ github.sha }}'
